import {
  Film,
  Star,
  Globe,
  PlayCircle,
  // TrendingUp,
  History,
  Heart,
} from "lucide-react";

export const data = {
  user: {
    name: "user",
    email: "user@gmail.com",
    avatar: "/avatars/shadcn.jpg",
  },
  navMain: [
    {
      title: "Phim mới cập nhật",
      url: "/",
      icon: Film,
      isActive: true,
    },
    {
      title: "Danh mục",
      url: "#",
      icon: PlayCircle,
      items: [
        { title: "Phim Lẻ", url: "/danh-muc/phim-le" },
        { title: "Phim Bộ", url: "/danh-muc/phim-bo" },
        { title: "Hoạt Hình", url: "/danh-muc/hoat-hinh" },
        { title: "Tv Shows", url: "/danh-muc/tv-shows" },
        { title: "Phim Vietsub", url: "/danh-muc/phim-vietsub" },
        { title: "Phim Thuyết Minh", url: "/danh-muc/phim-thuyet-minh" },
        { title: "Phim Lòng Tiếng", url: "/danh-muc/phim-khac" },
      ],
    },
    {
      title: "Thể loại",
      url: "#",
      icon: Star,
      items: [
        { title: "Hành Động", url: "/the-loai/hanh-dong" },
        { title: "Cổ Trang", url: "/the-loai/co-trang" },
        { title: "Chiến Tranh", url: "/the-loai/chien-tranh" },
        { title: "Viễn Tưởng", url: "/the-loai/vien-tuong" },
        { title: "Kinh Dị", url: "/the-loai/kinh-di" },
        { title: "Tài Liệu", url: "/the-loai/tai-lieu" },
        { title: "Bí Ẩn", url: "/the-loai/bi-an" },
        { title: "Phim 18+", url: "/the-loai/phim-18" },
        { title: "Tình Cảm", url: "/the-loai/tinh-cam" },
        { title: "Tâm Lý", url: "/the-loai/tam-ly" },
        { title: "Thể Thao", url: "/the-loai/the-thao" },
        { title: "Phiêu Lưu", url: "/the-loai/phieu-luu" },
        { title: "Âm Nhạc", url: "/the-loai/am-nhac" },
        { title: "Gia Đình", url: "/the-loai/gia-dinh" },
        { title: "Học Đường", url: "/the-loai/hoc-duong" },
        { title: "Hài Hước", url: "/the-loai/hai-huoc" },
        { title: "Hình Sự", url: "/the-loai/hinh-su" },
        { title: "Võ Thuật", url: "/the-loai/vo-thuat" },
        { title: "Khoa Học", url: "/the-loai/khoa-hoc" },
        { title: "Thần Thoại", url: "/the-loai/than-thoai" },
        { title: "Chính Kịch", url: "/the-loai/chinh-kich" },
        { title: "Kinh Điển", url: "/the-loai/kinh-dien" },
      ],
    },
    {
      title: "Quốc gia",
      url: "#",
      icon: Globe,
      items: [
        { title: "Trung Quốc", url: "/quoc-gia/trung-quoc" },
        { title: "Thái Lan", url: "/quoc-gia/thai-lan" },
        { title: "Hồng Kông", url: "/quoc-gia/hong-kong" },
        { title: "Pháp", url: "/quoc-gia/phap" },
        { title: "Đức", url: "/quoc-gia/duc" },
        { title: "Hà Lan", url: "/quoc-gia/ha-lan" },
        { title: "Mexico", url: "/quoc-gia/mexico" },
        { title: "Thụy Điển", url: "/quoc-gia/thuy-dien" },
        { title: "Philippines", url: "/quoc-gia/philippines" },
        { title: "Đan Mạch", url: "/quoc-gia/dan-mach" },
        { title: "Thụy Sĩ", url: "/quoc-gia/thuy-si" },
        { title: "Ukraina", url: "/quoc-gia/ukraina" },
        { title: "Hàn Quốc", url: "/quoc-gia/han-quoc" },
        { title: "Âu Mỹ", url: "/quoc-gia/au-my" },
        { title: "Ấn Độ", url: "/quoc-gia/an-do" },
        { title: "Canada", url: "/quoc-gia/canada" },
        { title: "Tây Ban Nha", url: "/quoc-gia/tay-ban-nha" },
        { title: "Indonesia", url: "/quoc-gia/indonesia" },
        { title: "Ba Lan", url: "/quoc-gia/ba-lan" },
        { title: "Malaysia", url: "/quoc-gia/malaysia" },
        { title: "Bồ Đào Nha", url: "/quoc-gia/bo-dao-nha" },
        { title: "UAE", url: "/quoc-gia/uae" },
        { title: "Châu Phi", url: "/quoc-gia/chau-phi" },
        { title: "Ả Rập Xê Út", url: "/quoc-gia/a-rap-xe-ut" },
        { title: "Nhật Bản", url: "/quoc-gia/nhat-ban" },
        { title: "Đài Loan", url: "/quoc-gia/dai-loan" },
        { title: "Anh", url: "/quoc-gia/anh" },
        { title: "Thổ Nhĩ Kỳ", url: "/quoc-gia/tho-nhi-ky" },
        { title: "Nga", url: "/quoc-gia/nga" },
        { title: "Úc", url: "/quoc-gia/uc" },
        { title: "Brazil", url: "/quoc-gia/brazil" },
        { title: "Ý", url: "/quoc-gia/y" },
        { title: "Na Uy", url: "/quoc-gia/na-uy" },
        { title: "Nam Phi", url: "/quoc-gia/nam-phi" },
        { title: "Việt Nam", url: "/quoc-gia/viet-nam" },
        { title: "Quốc Gia Khác", url: "/quoc-gia/khac" },
      ],
    },
    // {
    //   title: "Top IMDb",
    //   url: "#",
    //   icon: TrendingUp,
    //   items: [
    //     { title: "Top 250", url: "/top-imdb/top-250" },
    //     { title: "Đề xuất hôm nay", url: "/top-imdb/de-xuat-hom-nay" },
    //   ],
    // },
  ],
  navSecondary: [
    {
      title: "Lịch Sử Xem",
      url: "/lich-su-xem",
      icon: History,
    },
    {
      title: "Phim Yêu Thích",
      url: "/phim-yeu-thich",
      icon: Heart,
    },
  ],
  projects: [],
};
